name: Jekyll site CI

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        version: '>=10.18'
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && bundle install && jekyll build --trace --future"
        
    - name: Scan for A11y issues
      uses: devaradhanm/hello-world-docker-action@master
      with:
      # Artifact name
        site-dir: ${{ github.workspace }}/_site
      # Directory containing files to upload
        scan-url-relative-path: /  
        
    - name: Upload report artifact
      uses: actions/upload-artifact@v1.0.0
      with:
      # Artifact name
        name: reports
      # Directory containing files to upload
        path: ${{ github.workspace }}/_accessibility-reports
        
    - name: Upload site artifact
      uses: actions/upload-artifact@v1.0.0
      with:
      # Artifact name
        name: site
      # Directory containing files to upload
        path: ${{ github.workspace }}/_site  
